"""empty message

Revision ID: b75dde0125ef
Revises: 095acdc4b6a8
Create Date: 2022-02-15 16:45:08.754211

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'b75dde0125ef'
down_revision = '095acdc4b6a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('joinable_type', sa.String(length=20), nullable=False))
    op.add_column('memberships', sa.Column('joinable_id', sa.Integer(), nullable=False))
    op.drop_column('memberships', 'chat_id')
    op.drop_column('memberships', 'chat_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('chat_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('memberships', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('memberships', 'joinable_id')
    op.drop_column('memberships', 'joinable_type')
    # ### end Alembic commands ###
