"""empty message

Revision ID: 4649d180c953
Revises: ffdc0a98111c
Create Date: 2022-02-15 12:16:13.092154

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.environ.get("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '4649d180c953'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    if environment == "production":
        op.execute(f"ALTER TABLE conversations SET SCHEMA {SCHEMA};")                    
    op.create_table('friendships',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user1_id', sa.Integer(), nullable=False),
                    sa.Column('user2_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.String(length=64), nullable=False),
                    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    if environment == "production":
        op.execute(f"ALTER TABLE friendships SET SCHEMA {SCHEMA};")                    
    op.create_table('memberships',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('chat_type', sa.String(
                        length=20), nullable=False),
                    sa.Column('chat_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    if environment == "production":
        op.execute(f"ALTER TABLE memberships SET SCHEMA {SCHEMA};")  
    op.create_table('servers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('owner_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=20), nullable=False),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    if environment == "production":
        op.execute(f"ALTER TABLE servers SET SCHEMA {SCHEMA};")  
    op.create_table('channels',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('server_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=20), nullable=False),
                    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    if environment == "production":
        op.execute(f"ALTER TABLE channels SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channels')
    op.drop_table('servers')
    op.drop_table('memberships')
    op.drop_table('friendships')
    op.drop_table('conversations')
    # ### end Alembic commands ###
