"""empty message

Revision ID: 9915ee40c3bb
Revises: 5143d84159ec
Create Date: 2022-02-24 10:41:28.854578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9915ee40c3bb'
down_revision = '5143d84159ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('imgUrl', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'imgUrl')
    # ### end Alembic commands ###
